### ISSUE TITLE
Create a `v1` major version tag

### ISSUE THREAD

**Issue by CedX** [lix-pm/setup-lix#4]
We should be able to use the latest "v1" version of this action without editing our workflow files each time. 
See https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management

**Comment by kevinresol** [comment]
I am not sure about this, can't we just stick with master? i.e. `uses: lix-pm/setup-lix@master`

**Comment by CedX** [comment]
The main purpose of version tags is "predictability". This avoids:
- "They committed a bug on the master branch and now my CI is broken!"
- "They renamed the master branch to `main` and now my CI is broken!"

I don't want to place a burden on you. So if you think that it's more convenient to always use `master`, I'm fine with that 😄
